"""Reporter — SVG badge + HTML report for DCP-2.0 leaderboard.

Zero heavy deps: stdlib only (pathlib, json, html).
"""

from __future__ import annotations

import html
import json
import pathlib
from typing import Any, Dict


def generate_svg_badge(label: str, value: str, color: str = "#4c1") -> str:
    """Generate a shields.io-style SVG badge (byte-deterministic, no timestamp)."""
    # Simple flat badge: label (grey) + value (color)
    # Width estimation: ~7px per char + padding
    lw = max(40, len(label) * 7 + 12)
    vw = max(40, len(value) * 7 + 12)
    total = lw + vw
    # Escape XML
    label_e = html.escape(label)
    value_e = html.escape(value)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{total}" height="20" role="img" aria-label="{label_e}: {value_e}">
  <linearGradient id="s" x2="0" y2="100%">
    <stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/>
  </linearGradient>
  <clipPath id="r"><rect width="{total}" height="20" rx="3" fill="#fff"/></clipPath>
  <g clip-path="url(#r)">
    <rect width="{lw}" height="20" fill="#555"/>
    <rect x="{lw}" width="{vw}" height="20" fill="{color}"/>
    <rect width="{total}" height="20" fill="url(#s)"/>
  </g>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11">
    <text x="{lw / 2}" y="14">{label_e}</text>
    <text x="{lw + vw / 2}" y="14">{value_e}</text>
  </g>
</svg>"""


def write_svg_badge(path: str | pathlib.Path, label: str, value: str, color: str = "#4c1") -> pathlib.Path:
    p = pathlib.Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    # LF deterministic, no timestamp
    p.write_text(generate_svg_badge(label, value, color), encoding="utf-8", newline="\n")
    return p


def generate_html_report(leaderboard_data: Dict[str, Any]) -> str:
    """Generate a static interactive HTML comparison site (deterministic, no external JS)."""
    proto = html.escape(str(leaderboard_data.get("protocol_version", "DCP-2.0")))
    ts = leaderboard_data.get("timestamp", 0)
    leaderboard = leaderboard_data.get("leaderboard", [])
    receipts = leaderboard_data.get("receipts", [])

    rows = ""
    for idx, row in enumerate(leaderboard, 1):
        label = html.escape(row.get("archetype_label", row.get("framework", "?")))
        rec_pct = row.get("recovery_rate_pct", row.get("recovery_rate_pct", 0))
        w_token = row.get("avg_W_token_pct", row.get("avg_duplicate_token_waste_pct", 0))
        t_resume = row.get("avg_T_resume_ms", row.get("avg_recovery_latency_ms", 0))
        c_fail = row.get("total_C_fail", row.get("state_corruptions", 0))
        status = "CONFORMANT" if rec_pct == 100.0 and w_token < 5.0 else "NON-CONFORMANT"
        badge = "🟢" if status == "CONFORMANT" else "🔴"
        medal = "🥇" if idx == 1 else ("🥈" if idx == 2 else f"{idx}")
        rows += f"<tr><td>{medal}</td><td>{label}</td><td>{rec_pct}%</td><td>{w_token}%</td><td>{t_resume} ms</td><td>{c_fail}</td><td>{badge} {status}</td></tr>\n"

    receipts_json = html.escape(json.dumps(receipts[:20], indent=2)[:8000]) if receipts else "[]"

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>LetItLoop DCP-2.0 Leaderboard — {proto}</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
body{{font-family:system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif;max-width:960px;margin:40px auto;padding:0 16px;line-height:1.5}}
table{{border-collapse:collapse;width:100%}} th,td{{border:1px solid #ddd;padding:8px;text-align:left}} th{{background:#f5f5f5}} tr:nth-child(even){{background:#fafafa}}
.badge{{display:inline-block;padding:4px 8px;border-radius:3px;color:#fff;font-weight:600}} .pass{{background:#4c1}} .fail{{background:#e05d44}}
</style>
</head>
<body>
<h1>🏆 Durability Conformance Protocol ({proto}) Leaderboard</h1>
<p>Empirical crash-resilience matrix under physical OS <code>SIGKILL</code> fault injection. Generated at <code>{ts}</code>.</p>
<table>
<thead><tr><th>Rank</th><th>Archetype</th><th>Crash Recovery</th><th>W_token</th><th>T_resume</th><th>C_fail</th><th>Status</th></tr></thead>
<tbody>
{rows}
</tbody>
</table>
<details><summary>Raw receipts (first 20)</summary><pre>{receipts_json}</pre></details>
<hr><p><sub>Generated by <code>agent-durability-bench</code> — <code>letitloop/conformance/reporter.py</code></sub></p>
</body>
</html>"""


def write_html_report(path: str | pathlib.Path, leaderboard_data: Dict[str, Any]) -> pathlib.Path:
    p = pathlib.Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(generate_html_report(leaderboard_data), encoding="utf-8", newline="\n")
    return p


def write_badges(
    leaderboard_data: Dict[str, Any], out_dir: str | pathlib.Path = "docs/badges"
) -> Dict[str, pathlib.Path]:
    """Generate SVG shields for leaderboard top entries (deterministic)."""
    out = pathlib.Path(out_dir)
    # Overall best
    leaderboard = leaderboard_data.get("leaderboard", [])
    if not leaderboard:
        return {}
    best = leaderboard[0]
    # Durability score = recovery_rate_pct
    dur_val = f"{best.get('recovery_rate_pct', 0)}%"
    dur_color = "#4c1" if best.get("recovery_rate_pct", 0) == 100 else "#e05d44"
    waste_val = f"{best.get('avg_W_token_pct', best.get('avg_duplicate_token_waste_pct', 0))}%"
    waste_color = "#4c1" if best.get("avg_W_token_pct", 0) < 5 else "#fe7d37"
    paths = {}
    paths["durability_score"] = write_svg_badge(out / "durability_score.svg", "durability", dur_val, dur_color)
    paths["token_waste"] = write_svg_badge(out / "token_waste.svg", "token waste", waste_val, waste_color)
    return paths
